# syntax=docker/dockerfile:1

FROM node:20-bookworm-slim
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json package-lock.json ./
RUN npm ci

EXPOSE 3000

CMD ["npm","run","dev","--","-H","0.0.0.0","-p","3000"]

